# Window settings
[window]
padding	= { x = 5, y = 5}
decorations	= "buttonless"

# Font settings
# agave typeface (https://github.com/blobject/agave.git)
# nerd fonts (https://github.com/ryanoasis/nerd-fonts)
[font]
normal	= { family = "Agave Nerd Font Mono", style = "Regular" }
bold	= { family = "Agave Nerd Font Mono", style = "Bold" }
size	= 16

# Colors (https://github.com/nordtheme/alacritty)
# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'
